/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_VentanaPrincipal;

public class FRM_VentanaPrincipal extends javax.swing.JFrame {

    Controlador_FRM_VentanaPrincipal controlador;

    public FRM_VentanaPrincipal() {
        initComponents();
        this.controlador = new Controlador_FRM_VentanaPrincipal(this);
        agregarEventos();
    }

    public void agregarEventos() {
        this.jb_Agregar.addActionListener(controlador);
        this.jb_LlamarCliente.addActionListener(controlador);
        this.jb_Mayor.addActionListener(controlador);
        this.jb_Menor.addActionListener(controlador);
        this.jb_Reporte.addActionListener(controlador);
        this.jb_Cancelar.addActionListener(controlador);
        this.jb_Modificar.addActionListener(controlador);
    }

    public void limpiarInterfaz() {
        this.jtf_Edad.setText("");
        this.jtf_Nombre.setText("");
        this.jtf_Cedula.setText("");
        this.jtf_FechaCita.setText("");
    }

    public int devolverEdad(){
        return Integer.parseInt(this.jtf_Edad.getText().trim());
    }
    

    public String devolverNombre() {
        return this.jtf_Nombre.getText();
    }

    public int devolverNumeroCedula() {
        return Integer.parseInt(this.jtf_Cedula.getText().trim());
    }
    public String devolverFechaCita() {
        return this.jtf_FechaCita.getText();
    }

  
    
    public void imprimirAgregar(String texto){
        this.jTextArea1.setText(texto);
    }
    public void imprimirEnLlamarCliente(String texto){
        this.jta_LlamarCliente.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_Edad = new javax.swing.JTextField();
        jtf_Nombre = new javax.swing.JTextField();
        jtf_Cedula = new javax.swing.JTextField();
        jb_LlamarCliente = new javax.swing.JButton();
        jb_Agregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_LlamarCliente = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jb_Menor = new javax.swing.JButton();
        jb_Mayor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtf_FechaCita = new javax.swing.JTextField();
        jb_Reporte = new javax.swing.JButton();
        jb_Cancelar = new javax.swing.JButton();
        jb_Modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setText("Edad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setText("Cedula");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        getContentPane().add(jtf_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 230, -1));
        getContentPane().add(jtf_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 230, -1));
        getContentPane().add(jtf_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 230, -1));

        jb_LlamarCliente.setText("Llamar Cliente");
        getContentPane().add(jb_LlamarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jb_Agregar.setText("Agregar");
        getContentPane().add(jb_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jta_LlamarCliente.setColumns(20);
        jta_LlamarCliente.setRows(5);
        jScrollPane2.setViewportView(jta_LlamarCliente);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 180, 140));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, 140));

        jb_Menor.setText("<");
        getContentPane().add(jb_Menor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jb_Mayor.setText(">");
        getContentPane().add(jb_Mayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel3.setText("Fecha de la cita:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        getContentPane().add(jtf_FechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, -1));

        jb_Reporte.setText("Reporte");
        getContentPane().add(jb_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jb_Cancelar.setText("Cancelar Cita");
        jb_Cancelar.setActionCommand("Cancelar");
        getContentPane().add(jb_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jb_Modificar.setText("Modificar");
        jb_Modificar.setActionCommand("Modificar");
        getContentPane().add(jb_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jb_Agregar;
    private javax.swing.JButton jb_Cancelar;
    private javax.swing.JButton jb_LlamarCliente;
    private javax.swing.JButton jb_Mayor;
    private javax.swing.JButton jb_Menor;
    private javax.swing.JButton jb_Modificar;
    private javax.swing.JButton jb_Reporte;
    private javax.swing.JTextArea jta_LlamarCliente;
    private javax.swing.JTextField jtf_Cedula;
    private javax.swing.JTextField jtf_Edad;
    private javax.swing.JTextField jtf_FechaCita;
    private javax.swing.JTextField jtf_Nombre;
    // End of variables declaration//GEN-END:variables
}
